"""
Data models for the Field Service Allocation Engine.

Technician = mobile resource (location, skill levels, availability).
RepairRequest = job to be fulfilled (location, required skills with minimum levels, time window).
Assignment = pairing of technician to request with optional metadata.
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, root_validator


class Location(BaseModel):
    """Geographic location (lat/lng for map compatibility)."""

    lat: float = Field(..., description="Latitude")
    lng: float = Field(..., description="Longitude")

    def distance_to(self, other: "Location") -> float:
        """Euclidean distance in degree units (approximate; for scoring only)."""
        return ((self.lat - other.lat) ** 2 + (self.lng - other.lng) ** 2) ** 0.5


class TimeWindow(BaseModel):
    """A continuous time interval [start, end]."""

    start: datetime = Field(..., description="Window start (inclusive)")
    end: datetime = Field(..., description="Window end (inclusive)")

    def contains(self, t: datetime) -> bool:
        """True if t is within [start, end]."""
        return self.start <= t <= self.end

    def overlaps(self, other: "TimeWindow") -> bool:
        """True if this window overlaps the other (touching endpoint does not count)."""
        return self.start < other.end and other.start < self.end

    def duration_minutes(self) -> float:
        """Window duration in minutes."""
        return max(0.0, (self.end - self.start).total_seconds() / 60.0)


class Technician(BaseModel):
    """A field service technician (mobile resource)."""

    id: str = Field(..., description="Unique technician identifier")
    location: Location = Field(..., description="Current or home location")
    skills: dict[str, int] = Field(
        default_factory=dict,
        description="Skill name to proficiency level (1-10)",
    )
    availability: list[TimeWindow] = Field(
        default_factory=list,
        description="Time windows when the technician is available",
    )
    available_hours_per_week: float = Field(
        default=40.0,
        ge=0.0,
        description="Nominal available hours per week",
    )
    max_daily_jobs: Optional[int] = Field(default=None, description="Max jobs per day (optional cap)")
    max_travel_distance: Optional[float] = Field(
        default=0.35,
        ge=0.0,
        description="Max travel distance in coordinate units for any assignment",
    )
    home_base: Optional[Location] = Field(default=None, description="Home/base location (optional)")

    @root_validator
    def validate_skill_levels(cls, values: dict) -> dict:
        for skill, level in values.get("skills", {}).items():
            if level < 1 or level > 10:
                raise ValueError(f"Skill '{skill}' must have level in [1, 10], got {level}")
        return values


class RepairRequest(BaseModel):
    """A repair or maintenance request (job to be fulfilled)."""

    id: str = Field(..., description="Unique request identifier")
    location: Location = Field(..., description="Job site location")
    required_skills: dict[str, int] = Field(
        default_factory=dict,
        description="Required skill name to minimum proficiency level (1-10)",
    )
    time_window: TimeWindow = Field(..., description="Earliest/latest time the job can be done")
    priority: int = Field(default=3, ge=1, le=5, description="Priority 1 (low) to 5 (high)")
    estimated_duration: float = Field(
        default=60.0,
        ge=1.0,
        description="Estimated job duration in minutes",
    )
    service_fee: float = Field(
        default=150.0,
        ge=0.0,
        description="Revenue generated by completing the request",
    )
    customer_id: Optional[str] = Field(
        default=None,
        description="Customer ID (for prefer-same-technician soft constraint)",
    )

    @root_validator
    def validate_required_skill_levels(cls, values: dict) -> dict:
        for skill, min_level in values.get("required_skills", {}).items():
            if min_level < 1 or min_level > 10:
                raise ValueError(f"Required skill '{skill}' must have level in [1, 10], got {min_level}")
        return values


class Assignment(BaseModel):
    """A pairing of a technician to a repair request."""

    technician_id: str = Field(..., description="ID of assigned technician")
    request_id: str = Field(..., description="ID of assigned request")
    score: Optional[float] = Field(default=None, description="Utility score of this assignment")
    explanation: Optional[str] = Field(
        default=None,
        description="Human-readable reason for this assignment",
    )
    estimated_travel_distance: Optional[float] = Field(
        default=None,
        description="Estimated distance in coordinate units",
    )
    estimated_travel_time: Optional[float] = Field(
        default=None,
        description="Estimated travel time in minutes",
    )
    expected_revenue: Optional[float] = Field(
        default=None,
        description="Expected revenue from the request fee",
    )
    slot_start: Optional[datetime] = Field(
        default=None,
        description="Planned start time for the job",
    )
